services:
  db:
    restart: always
    image: postgres
    user: ${POSTGRES_USER}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose: 
      - 5432
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      db:
        condition: service_healthy
    build: .
    ports:
      - 8001:8001
    volumes:
      - .:/application

volumes:
  db-data: